export const ADD="ADD"
export const GET_TODO_REQUEST="GET_TODO_REQUEST";
export const GET_TODO_SUCCESS="GET_TODO_SUCCESS";
export const GET_TODO_FALIUR="GET_TODO_FALIUR";

export const POST_TODO_REQUEST="POST_TODO_REQUEST";
export const POST_TODO_SUCCESS="POST_TODO_SUCCESS";
export const POST_TODO_FALIUR="POST_TODO_FALIUR";


export const DELETE_TODO_REQUEST="DELETE_TODO_REQUEST";
export const DELETE_TODO_SUCCESS="DELETE_TODO_SUCCESS";
export const DELETE_TODO_FALIUR="DELETE_TODO_FALIUR";

export const UPDATE_TODO_REQUEST="UPDATE_TODO_REQUEST";
export const UPDATE_TODO_SUCCESS="UPDATE_TODO_SUCCESS";
export const UPDATE_TODO_FALIUR="UPDATE_TODO_FALIUR";
